# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20171114_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_type_id',
            field=models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1, verbose_name='设备类型'),
        ),
    ]
